services:
  - type: web
    name: screen-share-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_client.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: DEBUG
        value: false
